import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  Navbar  from "@/components/Navbar"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <div className="flex min-h-screen flex-col items-center bg-gray-700">
    <Navbar /> 
    <div className="h-screen w-screen">
      <div className="h-full bg-white mx-12 rounded-3xl">
      {children}
      </div>
    </div>
    </div>
      </body>
    </html>
  );
}
